spring:
  jpa:
    open-in-view: false
  rabbitmq:
    template:
      exchange: "paymentprocessor-exchange"

application:
  clients:
    usernames:
      - user1
      - user2
  external:
    type1_payment_notification_url: 'https://www.google.com/lets_get_404'
    type2_payment_notification_url: 'https://www.google.com/'