spring:
  jpa:
    open-in-view: false
    properties:
      javax:
        persistence:
          lock:
            timeout: 0
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  rabbitmq:
    template:
      exchange: "paymentprocessor-exchange"

application:
  clients:
    usernames:
      - user1
      - user2
  external:
    type1_payment_notification_url: 'https://www.google.com/lets_get_404'
    type2_payment_notification_url: 'https://www.google.com/'