spring:
  jpa:
    open-in-view: false
  rabbitmq:
    template:
      exchange: "paymentprocessor-exchange"
      routing-key: "abc"

application:
  clients:
    usernames:
      - user1
      - user2